[package]
name = "tartarus-xkb"
version = "0.1.0"
authors = ["carrie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
notifica = "1.0.2"
regex = "1.3.4"
x11rb = "0.3.0"
